# Basic APISIX Configuration
apisix:
  node_listen:
    - port: 9080
    - port: 9443
      enable_http2: true

etcd:
  host: 
    - "http://etcd:2379"
  prefix: "/apisix"
  timeout: 30

nginx_config:
  worker_processes: auto
  worker_rlimit_nofile: 20480

plugins:
  - serverless-pre-function
  - serverless-post-function
  - proxy-rewrite
  - prometheus
  - echo
  - consumer-restriction
  - key-auth
  - jwt-auth
  - basic-auth
  - wolf-rbac
  - authz-keycloak
  - proxy-cache
  - kafka-proxy
  - skywalking
  - ssl
  - traffic-split
  - openid-connect
  - ext-plugin-pre-req
  - ext-plugin-post-req
